stages:
  get_data:
    cmd: python get_data.py
    deps:
      - get_data.py
    outs:
      - data/data_raw.csv
  train:
    cmd: python train_data.py
    deps:
      - train_data.py
      - data/data_raw.csv
    metrics:
      - metrics.json:
          cache: false
    plots:
      - confusion_matrix.png:
          cache: false